### BASE with Node.js and pnpm pre-installned
FROM node:22-alpine AS base

RUN npm install -g pnpm@10.10.0

### BUILD
FROM base as build

WORKDIR /app-build

RUN apk add --no-cache chromium

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
COPY packages/core/package.json packages/core/package.json
COPY apps/cv/package.json apps/cv/package.json
COPY apps/cv/scripts/build.ts apps/cv/scripts/build.ts
COPY apps/website/package.json apps/website/package.json

RUN pnpm install --frozen-lockfile

COPY . .

# defining args for env
ARG WS_PUBLIC_BASE_URL=https://websavva.dev
ARG WS_PUBLIC_BIO_FULL_NAME_EN=author
ARG WS_PUBLIC_BIO_FULL_NAME_RU=автор
ARG WS_PUBLIC_BIO_CAREER_START_DATE=1970.01.01
ARG WS_PUBLIC_BIO_BIRTH_DATE=1970.01.01
ARG WS_PUBLIC_BIO_SOCIAL_LINK_TELEGRAM=https://telegram.org/
ARG WS_PUBLIC_BIO_SOCIAL_LINK_GITHUB=https://github.com/
ARG WS_PUBLIC_BIO_LOCATION_EN
ARG WS_PUBLIC_BIO_LOCATION_RU
ARG WS_PUBLIC_BIO_PHONE_NUMBER
ARG WS_PUBLIC_BIO_EMAIL
ARG WS_PUBLIC_YM_ID

ENV NODE_ENV=production
ENV PORT=3000
ENV WS_PUBLIC_BASE_URL=${WS_PUBLIC_BASE_URL}
ENV WS_PUBLIC_BIO_FULL_NAME_EN=${WS_PUBLIC_BIO_FULL_NAME_EN}
ENV WS_PUBLIC_BIO_FULL_NAME_RU=${WS_PUBLIC_BIO_FULL_NAME_RU}
ENV WS_PUBLIC_BIO_CAREER_START_DATE=${WS_PUBLIC_BIO_CAREER_START_DATE}
ENV WS_PUBLIC_BIO_BIRTH_DATE=${WS_PUBLIC_BIO_BIRTH_DATE}
ENV WS_PUBLIC_BIO_SOCIAL_LINK_TELEGRAM=${WS_PUBLIC_BIO_SOCIAL_LINK_TELEGRAM}
ENV WS_PUBLIC_BIO_SOCIAL_LINK_GITHUB=${WS_PUBLIC_BIO_SOCIAL_LINK_GITHUB}
ENV WS_PUBLIC_YM_ID=${WS_PUBLIC_YM_ID}
ENV WS_PUBLIC_BIO_LOCATION_EN=${WS_PUBLIC_BIO_LOCATION_EN}
ENV WS_PUBLIC_BIO_LOCATION_RU=${WS_PUBLIC_BIO_LOCATION_RU}
ENV WS_PUBLIC_BIO_PHONE_NUMBER=${WS_PUBLIC_BIO_PHONE_NUMBER}
ENV WS_PUBLIC_BIO_EMAIL=${WS_PUBLIC_BIO_EMAIL}
ENV PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium-browser

RUN pnpm dev:prepare

RUN pnpm build

### PRODUCTION
FROM base as production

WORKDIR /app

# defining args for env
ARG WS_PUBLIC_BASE_URL=https://websavva.dev
ARG WS_PUBLIC_BIO_FULL_NAME_EN=author
ARG WS_PUBLIC_BIO_FULL_NAME_RU=автор
ARG WS_PUBLIC_BIO_CAREER_START_DATE=1970.01.01
ARG WS_PUBLIC_BIO_BIRTH_DATE=1970.01.01
ARG WS_PUBLIC_BIO_SOCIAL_LINK_TELEGRAM=https://telegram.org/
ARG WS_PUBLIC_BIO_SOCIAL_LINK_GITHUB=https://github.com/
ARG WS_PUBLIC_YM_ID
ARG WS_PUBLIC_BIO_LOCATION_EN
ARG WS_PUBLIC_BIO_LOCATION_RU
ARG WS_PUBLIC_BIO_PHONE_NUMBER
ARG WS_PUBLIC_BIO_EMAIL

ENV NODE_ENV=production
ENV PORT=3000
ENV WS_PUBLIC_BASE_URL=${WS_PUBLIC_BASE_URL}
ENV WS_PUBLIC_BIO_FULL_NAME_EN=${WS_PUBLIC_BIO_FULL_NAME_EN}
ENV WS_PUBLIC_BIO_FULL_NAME_RU=${WS_PUBLIC_BIO_FULL_NAME_RU}
ENV WS_PUBLIC_BIO_CAREER_START_DATE=${WS_PUBLIC_BIO_CAREER_START_DATE}
ENV WS_PUBLIC_BIO_BIRTH_DATE=${WS_PUBLIC_BIO_BIRTH_DATE}
ENV WS_PUBLIC_BIO_SOCIAL_LINK_TELEGRAM=${WS_PUBLIC_BIO_SOCIAL_LINK_TELEGRAM}
ENV WS_PUBLIC_BIO_SOCIAL_LINK_GITHUB=${WS_PUBLIC_BIO_SOCIAL_LINK_GITHUB}
ENV WS_PUBLIC_YM_ID=${WS_PUBLIC_YM_ID}
ENV WS_PUBLIC_BIO_LOCATION_EN=${WS_PUBLIC_BIO_LOCATION_EN}
ENV WS_PUBLIC_BIO_LOCATION_RU=${WS_PUBLIC_BIO_LOCATION_RU}
ENV WS_PUBLIC_BIO_PHONE_NUMBER=${WS_PUBLIC_BIO_PHONE_NUMBER}
ENV WS_PUBLIC_BIO_EMAIL=${WS_PUBLIC_BIO_EMAIL}

RUN apk add --no-cache curl

COPY --from=build /app-build/apps/website/.output/ .output

EXPOSE 3000

CMD node .output/server/index.mjs
