version: '3.8'

services:
  # Portfolio application
  portfolio:
    image: ghcr.io/websavva/portfolio:${WS_PUBLIC_RELEASE_VERSION}
    container_name: app
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3000
      - WS_PUBLIC_BASE_URL=https://websavva.dev
      - WS_PRIVATE_TELEGRAM_BOT_API_KEY=${WS_PRIVATE_TELEGRAM_BOT_API_KEY}
      - WS_PRIVATE_TELEGRAM_BOT_CHAT_ID=${WS_PRIVATE_TELEGRAM_BOT_CHAT_ID}
    networks:
      - portfolio
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Nginx reverse proxy
  nginx:
    image: nginx:1.25-alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      portfolio:
        condition: service_healthy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /ssl-certificates:/ssl-certificates
    networks:
      - portfolio
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/api/health"]
      interval: 5s
      timeout: 5s
      retries: 15
      start_period: 5s

networks:
  portfolio:
