### BASE with Node.js and pnpm pre-installned
FROM node:22-alpine AS base

RUN npm install -g pnpm@10.10.0

### BUILD
FROM base as build

WORKDIR /app-build

COPY package.json pnpm-lock.yaml ./

RUN pnpm install --frozen-lockfile

COPY . .

# defining args for env
ARG WS_PUBLIC_BASE_URL=https://websavva.dev
ARG WS_PUBLIC_BIO_FULL_NAME_EN=author
ARG WS_PUBLIC_BIO_FULL_NAME_RU=автор
ARG WS_PUBLIC_BIO_CAREER_START_DATE=1970.01.01
ARG WS_PUBLIC_BIO_BIRTH_DATE=1970.01.01
ARG WS_PUBLIC_BIO_SOCIAL_LINK_TELEGRAM=https://telegram.org/
ARG WS_PUBLIC_BIO_SOCIAL_LINK_GITHUB=https://github.com/
ARG WS_PUBLIC_YM_ID

ENV NODE_ENV=production
ENV PORT=3000
ENV WS_PUBLIC_BASE_URL=${WS_PUBLIC_BASE_URL}
ENV WS_PUBLIC_BIO_FULL_NAME_EN=${WS_PUBLIC_BIO_FULL_NAME_EN}
ENV WS_PUBLIC_BIO_FULL_NAME_RU=${WS_PUBLIC_BIO_FULL_NAME_RU}
ENV WS_PUBLIC_BIO_CAREER_START_DATE=${WS_PUBLIC_BIO_CAREER_START_DATE}
ENV WS_PUBLIC_BIO_BIRTH_DATE=${WS_PUBLIC_BIO_BIRTH_DATE}
ENV WS_PUBLIC_BIO_SOCIAL_LINK_TELEGRAM=${WS_PUBLIC_BIO_SOCIAL_LINK_TELEGRAM}
ENV WS_PUBLIC_BIO_SOCIAL_LINK_GITHUB=${WS_PUBLIC_BIO_SOCIAL_LINK_GITHUB}
ENV WS_PUBLIC_YM_ID=${WS_PUBLIC_YM_ID}

RUN pnpm build

### PRODUCTION
FROM base as production

WORKDIR /app

# defining args for env
ARG WS_PUBLIC_BASE_URL=https://websavva.dev
ARG WS_PUBLIC_BIO_FULL_NAME_EN=author
ARG WS_PUBLIC_BIO_FULL_NAME_RU=автор
ARG WS_PUBLIC_BIO_CAREER_START_DATE=1970.01.01
ARG WS_PUBLIC_BIO_BIRTH_DATE=1970.01.01
ARG WS_PUBLIC_BIO_SOCIAL_LINK_TELEGRAM=https://telegram.org/
ARG WS_PUBLIC_BIO_SOCIAL_LINK_GITHUB=https://github.com/
ARG WS_PUBLIC_YM_ID

ENV NODE_ENV=production
ENV PORT=3000
ENV WS_PUBLIC_BASE_URL=${WS_PUBLIC_BASE_URL}
ENV WS_PUBLIC_BIO_FULL_NAME_EN=${WS_PUBLIC_BIO_FULL_NAME_EN}
ENV WS_PUBLIC_BIO_FULL_NAME_RU=${WS_PUBLIC_BIO_FULL_NAME_RU}
ENV WS_PUBLIC_BIO_CAREER_START_DATE=${WS_PUBLIC_BIO_CAREER_START_DATE}
ENV WS_PUBLIC_BIO_BIRTH_DATE=${WS_PUBLIC_BIO_BIRTH_DATE}
ENV WS_PUBLIC_BIO_SOCIAL_LINK_TELEGRAM=${WS_PUBLIC_BIO_SOCIAL_LINK_TELEGRAM}
ENV WS_PUBLIC_BIO_SOCIAL_LINK_GITHUB=${WS_PUBLIC_BIO_SOCIAL_LINK_GITHUB}
ENV WS_PUBLIC_YM_ID=${WS_PUBLIC_YM_ID}

RUN apk add --no-cache curl

COPY --from=build /app-build/.output/ ./.output

EXPOSE 3000

CMD node .output/server/index.mjs
